### ISSUE TITLE
Data in swow-full-merged.jsonl.gz is less than original SWOW

### ISSUE THREAD

**Issue by ThinkingSlow** [U-Alberta/WordTies#1]
Hello Peiran, thanks for sharing the resources! 

I noticed that cues in swow-full-merged.jsonl.gz ends with "pronounciation", causing many cues in swow.csv cannot be found. Unsure what caused this. Wondering it it possible to provide the full version?  Thanks a lot!

**Comment by xavieryao** [comment]
Thanks for letting us know. The data file has been updated. I've also included a script that generates the data: https://github.com/U-Alberta/WordTies/blob/main/link-swow-and-kg.py

**Comment by ThinkingSlow** [comment]
Thanks Peiran!
